In [2]:
import pandas as pd

In [3]:
!pip install xlrd
!pip install openpyxl
csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

Requirement already satisfied: xlrd in c:\users\kiit0001\appdata\local\programs\python\python312\lib\site-packages (2.0.1)
Requirement already satisfied: openpyxl in c:\users\kiit0001\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\kiit0001\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

In [5]:
df

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [4]:
df.describe()

,Released,Music Recording Sales (millions),Claimed Sales (millions),Rating
count,8.000000,8.000000,8.000000,8.000000
mean,1979.250000,28.125000,46.125000,8.250000
std,5.800246,8.189322,8.271077,1.224745
min,1973.000000,20.600000,40.000000,6.500000
25%,1976.750000,23.300000,41.500000,7.375000
50%,1977.000000,26.750000,43.500000,8.250000
75%,1980.500000,28.975000,46.250000,9.125000
max,1992.000000,46.000000,65.000000,10.000000

In [7]:
df

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [18]:
xlsx_path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Datasets/TopSellingAlbums.xlsx'

await download(xlsx_path, "TopSellingAlbums.xlsx")
df = pd.read_excel("TopSellingAlbums.xlsx")
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

READING DATA FROM POKEMON DATASET(CSV FILE)

In [2]:
import pandas as pd

In [24]:
df=pd.read_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_data.csv')
#print(df.head(3))

In [5]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [21]:
#print(df[['Name','Type 1','HP']][0:5])
print(df.iloc[4:10])

   #                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
4  4                 Charmander   Fire     NaN  39      52       43       60
5  5                 Charmeleon   Fire     NaN  58      64       58       80
6  6                  Charizard   Fire  Flying  78      84       78      109
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159
9  7                   Squirtle  Water     NaN  44      48       65       50

   Sp. Def  Speed  Generation  Legendary
4       50     65           1      False
5       65     80           1      False
6       85    100           1      False
7       85    100           1      False
8      115    100           1      False
9       64     43           1      False

In [80]:
#print(df.iloc[7,1])
#for index,row in df.iterrows():
    #print(index,row['Name'])
df.loc[(df['Type 1']=='Dragon') & (df['Generation'].between(1,3))]
#set(df['Type 1'])

,#,Name,Type 1,Type 2,TotalHP,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
159,147,Dratini,Dragon,NaN,300,300,41,64,45,50,50,50,1
160,148,Dragonair,Dragon,NaN,420,420,61,84,65,70,70,70,1
161,149,Dragonite,Dragon,Flying,600,600,91,134,95,100,100,80,1
365,334,Altaria,Dragon,Flying,490,490,75,70,90,70,105,80,3
366,334,AltariaMega Altaria,Dragon,Fairy,590,590,75,110,110,110,105,80,3
406,371,Bagon,Dragon,NaN,300,300,45,75,60,40,30,50,3
407,372,Shelgon,Dragon,NaN,420,420,65,95,100,60,50,50,3
408,373,Salamence,Dragon,Flying,600,600,95,135,80,110,80,100,3
409,373,SalamenceMega Salamence,Dragon,Flying,700,700,95,145,130,120,90,120,3
417,380,Latias,Dragon,Psychic,600,600,80,80,90,110,130,110,3
418,380,LatiasMega Latias,Dragon,Psychic,700,700,80,100,120,140,150,110,3
419,381,Latios,Dragon,Psychic,600,600,80,90,80,130,110,110,3
420,381,LatiosMega Latios,Dragon,Psychic,700,700,80,130,100,160,120,110,3
425,384,Rayquaza,Dragon,Flying,680,680,105,150,90,150,90,95,3
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,780,105,180,100,180,100,115,3

In [41]:
df.sort_values(['Type 1','HP'],ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [5]:
df['TotalHP']= df.loc[:,'HP':'Speed'].sum(axis=1)
df.head(4)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,TotalHP
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625

In [6]:
cols=list(df.columns.values)
df= df[cols[0:4]+ [cols[-1]] +cols[4:12]]
df= df.loc[:, df.columns[df.columns.get_loc('#'):df.columns.get_loc('Speed') + 1].tolist() + ['Legendary','Generation']]

In [47]:
df.columns.values[10]='Agility'

In [4]:
df.head(4)

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,False,1
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1

In [83]:
df.to_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokedata_mod.csv',index=False)

In [10]:
df.to_excel(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokedata_mod.xlsx', index=False)

In [66]:
new_df=df.loc[(df['Type 1']=='Water') & (df['Type 2']=='Dark') & (df['HP']>50)]

In [75]:
new_df

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Agility,Legendary,Generation
0,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,False,1
1,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,False,3
2,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,False,3
3,342,Crawdaunt,Water,Dark,468,63,120,85,90,55,55,False,3
4,658,Greninja,Water,Dark,530,72,95,67,103,71,122,False,6

In [74]:
new_df.reset_index(drop=True,inplace=True)

In [76]:
new_df.to_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\filtered.csv')

In [84]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Agility,Legendary,Generation
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,False,1
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,False,1
12,9,Mega Blastoise,Water,NaN,630,79,103,120,135,115,78,False,1
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,False,1
23,18,Mega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,False,1
71,65,Mega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,False,1
87,80,Mega Slowbro,Water,Psychic,590,95,75,180,130,80,30,False,1
102,94,Mega Gengar,Ghost,Poison,600,60,65,80,170,95,130,False,1
124,115,Mega Kangaskhan,Normal,NaN,590,105,125,100,60,100,100,False,1
137,127,Mega Pinsir,Bug,Flying,600,65,155,120,65,90,105,False,1
141,130,Mega Gyarados,Water,Dark,640,95,155,109,70,130,81,False,1
154,142,Mega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,False,1
163,150,Mega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,True,1
164,150,Mega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,True,1
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,False,2
196,181,Mega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,False,2
224,208,Mega Steelix,Steel,Ground,610,75,125,230,55,95,30,False,2
229,212,Mega Scizor,Bug,Steel,600,70,150,140,65,100,75,False,2
232,214,Mega Heracross,Bug,Fighting,600,80,185,115,40,105,75,False,2
248,229,Mega Houndoom,Dark,Fire,600,75,90,90,140,90,115,False,2
268,248,Mega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,False,2
275,254,Mega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,False,3
279,257,Mega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,False,3
283,260,Mega Swampert,Water,Ground,635,100,150,110,95,110,70,False,3
306,282,Mega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,False,3
327,302,Mega Sableye,Dark,Ghost,480,50,85,125,85,115,20,False,3
329,303,Mega Mawile,Steel,Fairy,480,50,105,125,55,95,50,False,3
333,306,Mega Aggron,Steel,NaN,630,70,140,230,60,80,50,False,3
336,308,Mega Medicham,Fighting,Psychic,510,60,100,85,80,85,100,False,3
339,310,Mega Manectric,Electric,NaN,575,70,75,80,135,80,135,False,3
349,319,Mega Sharpedo,Water,Dark,560,70,140,70,110,65,105,False,3
354,323,Mega Camerupt,Fire,Ground,560,70,120,100,145,105,20,False,3
366,334,Mega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,False,3
387,354,Mega Banette,Ghost,NaN,555,64,165,75,93,83,75,False,3
393,359,Mega Absol,Dark,NaN,565,65,150,60,115,60,115,False,3
397,362,Mega Glalie,Ice,NaN,580,80,120,80,120,80,100,False,3
409,373,Mega Salamence,Dragon,Flying,700,95,145,130,120,90,120,False,3
413,376,Mega Metagross,Steel,Psychic,700,80,145,150,105,110,110,False,3
418,380,Mega Latias,Dragon,Psychic,700,80,100,120,140,150,110,True,3
420,381,Mega Latios,Dragon,Psychic,700,80,130,100,160,120,110,True,3
426,384,Mega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,True,3
476,428,Mega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,False,4
494,445,Mega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,False,4
498,448,Mega Lucario,Fighting,Steel,625,70,145,88,140,70,112,False,4
511,460,Mega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,False,4
527,475,Mega Gallade,Psychic,Fighting,618,68,165,95,65,115,110,False,4
591,531,Mega Audino,Normal,Fairy,545,103,60,126,80,126,50,False,5
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,True,6

In [26]:
import re

In [9]:
# Assume `df` is your larger DataFrame
df["Name"] = df["Name"].str.replace(r"(\w+)Mega \1", r"Mega \1", regex=True)

In [27]:
df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,False,1
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,False,6
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,False,6
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,False,6
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,False,6
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,True,6

In [12]:
orig=pd.read_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_data.csv')

In [13]:
df.to_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_data.csv', index=False)

In [19]:
df.loc[df['Name'].str.contains(r'^pi\D*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,False,1
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,False,1
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,False,1
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,False,1
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,False,1
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,False,2
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,False,2
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,False,2
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,False,4
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,False,5
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,False,5

In [31]:
df.loc[df['Type 1']=='Flame']

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
4,4,Charmander,Flame,NaN,309,39,52,43,60,50,65,False,1
5,5,Charmeleon,Flame,NaN,405,58,64,58,80,65,80,False,1
6,6,Charizard,Flame,Flying,534,78,84,78,109,85,100,False,1
7,6,Mega Charizard X,Flame,Dragon,634,78,130,111,130,85,100,False,1
8,6,Mega Charizard Y,Flame,Flying,634,78,104,78,159,115,100,False,1
42,37,Vulpix,Flame,NaN,299,38,41,40,50,65,65,False,1
43,38,Ninetales,Flame,NaN,505,73,76,75,81,100,100,False,1
63,58,Growlithe,Flame,NaN,350,55,70,45,70,50,60,False,1
64,59,Arcanine,Flame,NaN,555,90,110,80,100,80,95,False,1
83,77,Ponyta,Flame,NaN,410,50,85,55,65,65,90,False,1
84,78,Rapidash,Flame,NaN,500,65,100,70,80,80,105,False,1
135,126,Magmar,Flame,NaN,495,65,95,57,100,85,93,False,1
147,136,Flareon,Flame,NaN,525,65,130,60,95,110,65,False,1
158,146,Moltres,Flame,Flying,580,90,100,90,125,85,90,True,1
169,155,Cyndaquil,Flame,NaN,309,39,52,43,60,50,65,False,2
170,156,Quilava,Flame,NaN,405,58,64,58,80,65,80,False,2
171,157,Typhlosion,Flame,NaN,534,78,84,78,109,85,100,False,2
236,218,Slugma,Flame,NaN,250,40,40,40,70,40,20,False,2
237,219,Magcargo,Flame,Rock,410,50,50,120,80,80,30,False,2
259,240,Magby,Flame,NaN,365,45,75,37,70,55,83,False,2
263,244,Entei,Flame,NaN,580,115,115,85,90,75,100,True,2
270,250,Ho-oh,Flame,Flying,680,106,130,90,110,154,90,True,2
276,255,Torchic,Flame,NaN,310,45,60,40,70,50,45,False,3
277,256,Combusken,Flame,Fighting,405,60,85,60,85,60,55,False,3
278,257,Blaziken,Flame,Fighting,530,80,120,70,110,70,80,False,3
279,257,Mega Blaziken,Flame,Fighting,630,80,160,80,130,80,100,False,3
352,322,Numel,Flame,Ground,305,60,60,40,65,45,35,False,3
353,323,Camerupt,Flame,Ground,460,70,100,70,105,75,40,False,3
354,323,Mega Camerupt,Flame,Ground,560,70,120,100,145,105,20,False,3
355,324,Torkoal,Flame,NaN,470,70,85,140,85,70,20,False,3
435,390,Chimchar,Flame,NaN,309,44,58,44,58,44,61,False,4
436,391,Monferno,Flame,Fighting,405,64,78,52,78,52,81,False,4
437,392,Infernape,Flame,Fighting,534,76,104,71,104,71,108,False,4
518,467,Magmortar,Flame,NaN,540,75,95,67,125,95,83,False,4
542,485,Heatran,Flame,Steel,600,91,90,106,130,106,77,True,4
557,498,Tepig,Flame,NaN,308,65,63,45,45,45,45,False,5
558,499,Pignite,Flame,Fighting,418,90,93,55,70,55,55,False,5
559,500,Emboar,Flame,Fighting,528,110,123,65,100,65,65,False,5
572,513,Pansear,Flame,NaN,316,50,53,48,53,48,64,False,5
573,514,Simisear,Flame,NaN,498,75,98,63,98,63,101,False,5
614,554,Darumaka,Flame,NaN,315,70,90,45,15,45,50,False,5
615,555,DarmanitanStandard Mode,Flame,NaN,480,105,140,55,30,55,95,False,5
616,555,DarmanitanZen Mode,Flame,Psychic,540,105,30,105,140,105,55,False,5
692,631,Heatmor,Flame,NaN,484,85,97,66,105,66,65,False,5
721,653,Fennekin,Flame,NaN,307,40,45,40,62,60,60,False,6
722,654,Braixen,Flame,NaN,409,59,59,58,90,70,73,False,6
723,655,Delphox,Flame,Psychic,534,75,69,72,114,100,104,False,6
730,662,Fletchinder,Flame,Flying,382,62,73,55,56,52,84,False,6
731,663,Talonflame,Flame,Flying,499,78,81,71,74,69,126,False,6
735,667,Litleo,Flame,Normal,369,62,50,58,73,54,72,False,6
736,668,Pyroar,Flame,Normal,507,86,68,72,109,66,106,False,6
799,721,Volcanion,Flame,Water,600,80,110,120,130,90,70,True,6

In [29]:
df.loc[df['Type 1']=='Fire','Type 1'] = 'Flame'

In [34]:
df.to_excel(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_mod.xlsx', index=False)

In [36]:
df.head()

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,False,1
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1
4,4,Charmander,Flame,NaN,309,39,52,43,60,50,65,False,1

In [84]:
df.to_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_mod.csv', index=False)

In [66]:
df.groupby(['Type 1']).mean(numeric_only=True).sort_values('TotalHP',ascending=False)
#df.head()

,#,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
Type 1,,,,,,,,,,
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,0.375000,3.875000
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,0.148148,3.851852
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,0.500000,5.500000
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,0.245614,3.385965
Flame,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,0.096154,3.211538
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,0.090909,3.454545
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,0.064516,4.032258
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,0.090909,3.272727
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,0.062500,4.187500
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,0.125000,3.156250
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,0.083333,3.541667
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,0.035714,2.857143
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,0.042857,3.357143
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,0.000000,3.370370
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,0.058824,4.117647
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,0.020408,3.051020
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,0.000000,2.535714
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,0.000000,3.217391

In [75]:
df['Count']=1
df
#df.groupby(['Type 1']).count()

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation,Count
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,False,1,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,False,1,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,False,1,1
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1,1
4,4,Charmander,Flame,NaN,309,39,52,43,60,50,65,False,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,True,6,1
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,True,6,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,True,6,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,True,6,1
799,721,Volcanion,Flame,Water,600,80,110,120,130,90,70,True,6,1

In [80]:
df.groupby(['Type 1','Type 2']).count()['Count']

,#,Name,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation,Count
Type 1,,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27,27
Flame,52,52,24,52,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112,112

In [101]:
new_df=pd.DataFrame(columns=df.columns)

for data in pd.read_csv(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_mod.csv', chunksize=25):
    results= data.groupby(['Type 1']).count()
    new_df=pd.concat([new_df,results])

new_df

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation,Count
Bug,7,7,NaN,5,7,7,7,7,7,7,7,7,7,7.0
Flame,5,5,NaN,3,5,5,5,5,5,5,5,5,5,5.0
Grass,4,4,NaN,4,4,4,4,4,4,4,4,4,4,4.0
Normal,5,5,NaN,4,5,5,5,5,5,5,5,5,5,5.0
Water,4,4,NaN,0,4,4,4,4,4,4,4,4,4,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ghost,10,10,NaN,10,10,10,10,10,10,10,10,10,10,10.0
Ice,2,2,NaN,0,2,2,2,2,2,2,2,2,2,2.0
Psychic,2,2,NaN,2,2,2,2,2,2,2,2,2,2,2.0
Rock,2,2,NaN,2,2,2,2,2,2,2,2,2,2,2.0
Steel,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1.0

In [100]:
import pandas as pd
df=pd.read_excel(r'C:\Users\KIIT0001\OneDrive\Desktop\Coding\Pythonscripts\Datasets\pokemon_mod.xlsx')
df

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,False,1
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1
4,4,Charmander,Flame,NaN,309,39,52,43,60,50,65,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,True,6
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,True,6
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,True,6
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,True,6
799,721,Volcanion,Flame,Water,600,80,110,120,130,90,70,True,6

In [102]:
df.head()

,#,Name,Type 1,Type 2,TotalHP,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,False,1
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,False,1
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,False,1
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,False,1
4,4,Charmander,Flame,NaN,309,39,52,43,60,50,65,False,1